name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev libssl-dev zlib1g-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython
        
    - name: Accept Android licenses automatically
      run: |
        mkdir -p $HOME/.android
        echo "y" > $HOME/.android/agreed-to-android-sdk-license
        touch $HOME/.android/repositories.cfg
        yes | sdkmanager --licenses >/dev/null 2>&1 || true
        echo "Licenses accepted"
        
    - name: Pre-download Android SDK components
      run: |
        buildozer android debug || true
        
    - name: Accept licenses again (if needed)
      run: |
        yes | sdkmanager --licenses >/dev/null 2>&1 || true
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: budget-tracker-apk
        path: bin/*.apk
        if-no-files-found: error
